#' Bootstrap Randomization Test Inference
#'
#' Abstract class implementing the bootstrap randomization test (BRT), a hybrid of the
#' nonparametric bootstrap and the randomization test of Fisher's sharp null.
#'
#' @description
#' Each of the \code{B} null draws is generated by (1) resampling \code{n} subject rows
#' \emph{with replacement} from the observed data and (2) drawing one fresh assignment
#' vector \code{w} from the actual experimental design run on the resampled covariates.
#' The test statistic computed on each such draw forms a null distribution against which
#' the observed statistic (actual data, actual \code{w}) is compared.
#'
#' @details
#' \strong{Why this is valid: the sharp null makes the science table fully known.}
#' Under Fisher's sharp null \eqn{H_0: y_i(0) = y_i(1) = y_i} for all \eqn{i}, the observed
#' outcome is the outcome regardless of assignment, so each observed row \eqn{(x_i, y_i)}
#' is a complete description of that subject: it can be paired with any \eqn{w} and the
#' outcome is still correct. Resampling rows and drawing a fresh \eqn{w} therefore
#' simulates an entire new experiment — new subjects from \eqn{\hat{F}_n} (the empirical
#' distribution of subjects), new assignment from the true, known assignment mechanism —
#' under the assumption that outcomes do not respond to treatment. Both simulation
#' ingredients are faithful to the real data-generating process under \eqn{H_0}: the
#' assignment mechanism is exact (drawn from the actual design, including sequential
#' covariate-dependent designs, since the design depends only on the covariates), and the
#' subject distribution is approximately right by the usual bootstrap argument
#' \eqn{\hat{F}_n \to F}. The \eqn{B} statistics thus consistently estimate the
#' unconditional null sampling distribution of the statistic; if \eqn{H_0} holds, the
#' observed statistic is one genuine draw from that distribution, so the p-value is
#' asymptotically uniform. If \eqn{H_0} is false, the construction \emph{still} generates
#' the null distribution (it forcibly treats \eqn{y} as invariant to \eqn{w}) while the
#' observed statistic drifts into the tail — that asymmetry is the source of power.
#'
#' \strong{How it differs from the pure randomization test.} The classic randomization
#' test conditions on the realized sample (the "science table") and is exact for any
#' \eqn{n}. The BRT is unconditional: it targets the distribution of the statistic over
#' both subject sampling and randomization, so its validity is only asymptotic
#' (inheriting the usual bootstrap smoothness/moment conditions), and the null tested is
#' the compound "sharp null AND subjects are i.i.d. draws from \eqn{F}". Exactness is
#' traded for a population-level (superpopulation) interpretation. Equivalently, the BRT
#' is a parametric bootstrap test whose "parameter" is the pair (\eqn{F}, design): the
#' design part is known exactly, \eqn{F} is plugged in via \eqn{\hat{F}_n}, and the sharp
#' null is precisely what makes \eqn{\hat{F}_n} estimable from one arm-agnostic dataset.
#' The pure randomization test is the special case where \eqn{F} is conditioned away.
#'
#' \strong{Caveats.} (1) Sampling with replacement creates exact covariate ties that never
#' occur in the original data; for matching designs, duplicates are perfect matches, so
#' bootstrap experiments are systematically better matched than fresh draws from \eqn{F}
#' would be — a persistent (not vanishing) finite-\eqn{n} perturbation of the null
#' distribution for match-dependent statistics. (Here, matched structure is carried by the
#' pair-aware bootstrap resampler and fresh \code{w} draws follow the design's own
#' randomization distribution via \code{draw_ws_according_to_design}, consistent with the
#' package's randomization test.) (2) For sequential designs the bootstrap sample needs an
#' arrival order; the i.i.d. resampling order plays that role, matching the i.i.d.-arrivals
#' assumption of the KK designs. (3) Studentization is not needed for validity but, as with
#' any bootstrap test, an asymptotically pivotal statistic improves the level's rate of
#' convergence.
#'
#' Users do not instantiate this class directly: every concrete inference class in the
#' package inherits from it, so its methods (\code{compute_rand_bootstrap_two_sided_pval},
#' \code{approximate_rand_bootstrap_distribution_beta_hat_T}) are available on any
#' inference object. See \code{\link{InferenceRandBootstrapCI}} for the companion
#' confidence interval.
#'
#' @examples
#' \dontrun{
#' seq_des = DesignSeqOneByOneKK14$new(n = 100, response_type = "continuous")
#' # ... run the experiment: add subjects and responses ...
#' seq_des_inf = InferenceAllSimpleMeanDiff$new(seq_des)
#' seq_des_inf$compute_rand_bootstrap_two_sided_pval(B = 501)
#' }
#' @keywords internal
InferenceRandBootstrap = R6::R6Class("InferenceRandBootstrap",
	lock_objects = FALSE,
	inherit = InferenceNonParamBootstrap,
	public = list(
		#' @description Computes the bootstrap randomization null distribution of the test
		#'   statistic under Fisher's sharp null (shifted by \code{delta}): each draw resamples
		#'   subject rows with replacement and draws one fresh assignment vector from the design.
		#'
		#' @param B  					Number of bootstrap randomization draws. Default 501.
		#' @param delta  				The null treatment effect (on the \code{transform_responses}
		#'   scale). Default 0.
		#' @param transform_responses  Type of response transformation used to impose the
		#'   sharp null shift for nonzero \code{delta}. Default "none".
		#' @param show_progress  		A flag indicating whether a progress bar should be displayed.
		#' @param debug  				If \code{TRUE}, return a list with the distribution values and
		#'   per-iteration diagnostics including error messages, warning messages, counts of each,
		#'   and summary proportions for iterations with errors, warnings, and illegal (non-finite)
		#'   values. Runs serially. Default \code{FALSE}.
		#' @param bootstrap_type 		Optional bootstrap-resampling scheme; see
		#'   \code{approximate_bootstrap_distribution_beta_hat_T} for legal values. Default \code{NULL}.
		#' @param rand_bootstrap_draws 	Optional pre-generated draws (as returned by the private
		#'   method \code{generate_rand_bootstrap_draws}) enabling common random numbers across
		#'   calls with different \code{delta} values (used by the CI inversion). Default \code{NULL}.
		#' @param zero_one_logit_clamp The clamping amount for exact 0 and 1 values when logging.
		#' @return 	When \code{debug = FALSE} (default), a numeric vector of length \code{B}
		#'   containing the null-distribution draws. When \code{debug = TRUE}, a list with:
		#'   \code{values}, \code{errors}, \code{warnings}, \code{num_errors}, \code{num_warnings},
		#'   \code{prop_iterations_with_errors}, \code{prop_iterations_with_warnings}, and
		#'   \code{prop_illegal_values}.
		approximate_rand_bootstrap_distribution_beta_hat_T = function(B = 501, delta = 0, transform_responses = "none", show_progress = TRUE, debug = FALSE, bootstrap_type = NULL, rand_bootstrap_draws = NULL, zero_one_logit_clamp = .Machine$double.eps){
			private$active_resampling_operation = "rand_bootstrap"
			on.exit(private$active_resampling_operation <- NULL, add = TRUE)
			if (should_run_asserts()) {
				private$assert_design_supports_resampling("Bootstrap randomization inference")
				private$assert_valid_bootstrap_type(bootstrap_type)
				assertNumeric(delta); assertCount(B, positive = TRUE); assertFlag(debug)
			}
			draws_supplied = !is.null(rand_bootstrap_draws)
			cache_key = paste(
				as.integer(B),
				formatC(as.numeric(delta), digits = 17, format = "fg", flag = "#"),
				transform_responses,
				if (draws_supplied) attr(rand_bootstrap_draws, "draws_id") else "fresh",
				sep = "|"
			)
			if (is.null(private$cached_values$rand_boot_distr_cache)) private$cached_values$rand_boot_distr_cache = list()
			if (!isTRUE(debug) && !is.null(private$cached_values$rand_boot_distr_cache[[cache_key]])) {
				return(private$cached_values$rand_boot_distr_cache[[cache_key]])
			}
			if (private$verbose) cat("Computing bootstrap randomization distribution...\n")
			has_custom_randomization_statistic =
				!is.null(private[["custom_randomization_statistic_function"]]) ||
				!is.null(private[["compiled_cpp_stat_fn"]])
			has_fast_kernel = !has_custom_randomization_statistic &&
				private$has_private_method("compute_fast_rand_bootstrap_distr")
			# Smoothed draws carry per-draw noise the C++ kernel cannot see; force worker/iteration path.
			if (has_fast_kernel && draws_supplied && length(rand_bootstrap_draws) > 0L && !is.null(rand_bootstrap_draws[[1L]][["smooth_noise"]]))
				has_fast_kernel = FALSE
			if (!draws_supplied) {
				if (!is.null(private$seed)) {
					had_seed = exists(".Random.seed", envir = .GlobalEnv, inherits = FALSE)
					if (had_seed) old_seed = get(".Random.seed", envir = .GlobalEnv, inherits = FALSE)
					on.exit(
						if (had_seed) assign(".Random.seed", old_seed, envir = .GlobalEnv) else rm(".Random.seed", envir = .GlobalEnv),
						add = TRUE
					)
					set.seed(private$seed)
				}
				# The C++ batch kernel consumes pre-drawn assignment vectors, so materialize
				# them at generation time when a fast kernel is available.
				rand_bootstrap_draws = private$generate_rand_bootstrap_draws(B, bootstrap_type = bootstrap_type, materialize_w = has_fast_kernel)
			}
			# Under the sharp null with effect delta, the control potential outcomes are the
			# observed responses with the delta shift removed from the treated subjects.
			y0_full = if (delta != 0) {
				private$shift_randomization_responses(
					y = private$y,
					w = private$w,
					delta = delta,
					transform_responses = transform_responses,
					response_type = private$des_obj_priv_int$response_type,
					inverse = TRUE,
					zero_one_logit_clamp = zero_one_logit_clamp
				)
			} else {
				private$y
			}
			if (isTRUE(debug)) {
				debug_results = lapply(rand_bootstrap_draws, function(draw) {
					iter_warns = character(0)
					iter_errs = character(0)
					iter_val = withCallingHandlers(
						tryCatch(
							private$run_rand_bootstrap_iteration(draw, delta, transform_responses, y0_full, zero_one_logit_clamp),
							error = function(e) { iter_errs <<- c(iter_errs, conditionMessage(e)); NA_real_ }
						),
						warning = function(w) { iter_warns <<- c(iter_warns, conditionMessage(w)); invokeRestart("muffleWarning") }
					)
					list(val = as.numeric(iter_val)[1L], errors = iter_errs, warnings = iter_warns)
				})
				values = vapply(debug_results, function(x) as.numeric(x[["val"]])[1L], numeric(1))
				errors_list = lapply(debug_results, `[[`, "errors")
				warnings_list = lapply(debug_results, `[[`, "warnings")
				num_errors_vec = lengths(errors_list)
				num_warnings_vec = lengths(warnings_list)
				private$cached_values$rand_boot_distr_cache[[cache_key]] = values
				return(list(
					values = values,
					errors = errors_list,
					warnings = warnings_list,
					num_errors = num_errors_vec,
					num_warnings = num_warnings_vec,
					prop_iterations_with_errors = mean(num_errors_vec > 0),
					prop_iterations_with_warnings = mean(num_warnings_vec > 0),
					prop_illegal_values = mean(!is.finite(values))
				))
			}
			# Fastest path: a concrete class may provide a C++ batch kernel that evaluates the
			# whole null distribution in one call from (y0, row-index matrix, assignment matrix).
			# It returns NULL when it cannot handle the request (e.g. unmaterializable draws or
			# an unsupported transform), in which case we fall through to the standard paths.
			if (has_fast_kernel) {
				fast_distr = tryCatch(
					private$compute_fast_rand_bootstrap_distr(y0_full, rand_bootstrap_draws, delta, transform_responses, zero_one_logit_clamp),
					error = function(e) NULL
				)
				if (!is.null(fast_distr)) {
					fast_distr = as.numeric(fast_distr)
					private$cached_values$rand_boot_distr_cache[[cache_key]] = fast_distr
					return(fast_distr)
				}
			}
			# Fast path: reusable worker states avoid the per-iteration design/inference
			# duplication that dominates the cost of the standard path. Custom randomization
			# statistics are excluded (compute_bootstrap_worker_estimate computes the model
			# estimate), mirroring the pure randomization test's reused-worker gating.
			if (isTRUE(private$use_reusable_bootstrap_worker()) &&
				is.null(private$custom_randomization_statistic_function) &&
				is.null(private[["compiled_cpp_stat_fn"]])) {
				t0s = private$compute_rand_bootstrap_distribution_with_reused_workers(
					rand_bootstrap_draws = rand_bootstrap_draws,
					delta = delta,
					transform_responses = transform_responses,
					y0_full = y0_full,
					actual_cores = private$effective_parallel_cores("bootstrap", self$num_cores),
					show_progress = show_progress,
					zero_one_logit_clamp = zero_one_logit_clamp
				)
				if (!is.numeric(t0s)) t0s = as.numeric(t0s)
				private$cached_values$rand_boot_distr_cache[[cache_key]] = t0s
				return(t0s)
			}
			# Warm-up guard: run one iteration serially (twice, using the second timing to skip
			# cold-start penalties) and only parallelize if computation outweighs fork overhead.
			actual_cores = private$effective_parallel_cores("bootstrap", self$num_cores)
			if (actual_cores > 1L) {
				do_warmup_iter = function() {
					tryCatch(
						private$run_rand_bootstrap_iteration(rand_bootstrap_draws[[1L]], delta, transform_responses, y0_full, zero_one_logit_clamp),
						error = function(e) NA_real_
					)
				}
				system.time(do_warmup_iter())  # First call: discarded (cold-start overhead)
				t_warmup = system.time(do_warmup_iter())[[3]]  # Second call: representative cost
				fork_overhead_estimate = if (!is.null(get_global_fork_cluster())) 0.01 else 0.3
				if (!(t_warmup * B > fork_overhead_estimate * actual_cores))
					actual_cores = 1L
			}
			t0s = unlist(private$par_lapply(seq_along(rand_bootstrap_draws), function(idx) {
				tryCatch(
					suppressWarnings(private$run_rand_bootstrap_iteration(rand_bootstrap_draws[[idx]], delta, transform_responses, y0_full, zero_one_logit_clamp)),
					error = function(e) NA_real_
				)
			}, n_cores = actual_cores, show_progress = show_progress,
			export_list = list(
				rand_bootstrap_draws = rand_bootstrap_draws,
				delta = delta,
				transform_responses = transform_responses,
				y0_full = y0_full,
				zero_one_logit_clamp = zero_one_logit_clamp
			)))
			if (!is.numeric(t0s)) t0s = as.numeric(t0s)
			private$cached_values$rand_boot_distr_cache[[cache_key]] = t0s
			t0s
		},
		#' @description Computes a bootstrap randomization two-sided p-value for Fisher's sharp
		#'   null (shifted by \code{delta}): the observed statistic (actual data, actual \code{w})
		#'   is compared against the null distribution generated by resampling rows and drawing
		#'   fresh assignments from the design.
		#'
		#' @param B  					Number of bootstrap randomization draws. Default 501.
		#' @param delta  				The null treatment effect. Default 0.
		#' @param transform_responses  Type of response transformation for the sharp null shift.
		#'   The default "none" resolves by response type (logit for proportion, log for count
		#'   and survival, identity otherwise), matching \code{compute_rand_two_sided_pval}.
		#' @param na.rm 				Remove non-finite null draws. Default \code{TRUE}.
		#' @param show_progress  		A flag indicating whether a progress bar should be displayed.
		#' @param bootstrap_type 		Optional bootstrap-resampling scheme; see
		#'   \code{approximate_bootstrap_distribution_beta_hat_T} for legal values. Default \code{NULL}.
		#' @param rand_bootstrap_draws 	Optional pre-generated draws for common random numbers
		#'   across \code{delta} values. Default \code{NULL}.
		#' @param zero_one_logit_clamp The clamping amount for exact 0 and 1 values when logging.
		#' @param type  				Test statistic type. \code{"percentile"} (default) uses the raw
		#'   estimator as the BRT test statistic, giving an asymptotic p-value that inherits
		#'   the unconditional superpopulation validity of the BRT.
		#'   \code{"studentized"} divides each null draw's signed deviation from the null by its
		#'   per-draw standard error: \eqn{p = 2\min(P(z^0_b \ge z), P(z^0_b \le z))} where
		#'   \eqn{z^0_b = (t^0_b - \delta)/\hat{s}^0_b}; yields asymmetric CI under inversion.
		#'   \code{"symmetric-percentile-t"} uses the absolute pivot
		#'   \eqn{p = P(|t^0_b - \delta|/\hat{s}^0_b \ge |t - \delta|/\hat{s})}; CI is symmetric.
		#'   Both SE-based types require the class to expose \code{s_beta_hat_T}; fall back to
		#'   \code{"percentile"} if the SE is unavailable.
		#'   \code{"smoothed"} adds kernel noise \eqn{\varepsilon_b \sim N(0, \hat{\sigma}/\sqrt{n})}
		#'   to each resampled draw before imposing the null shift, reducing discreteness in the
		#'   null distribution. Only meaningful for continuous responses.
		#'
		#'   \strong{Theoretical justification.} Order-statistic/rank-based estimators (e.g. the
		#'   Hodges-Lehmann pseudo-median) take only finitely many values, so their bootstrap/
		#'   randomization null distribution is a step function; this both coarsens p-values and
		#'   destabilizes the \code{uniroot}-based \code{delta} search in
		#'   \code{\link{InferenceRandBootstrapCI}}'s \code{compute_rand_bootstrap_confidence_interval},
		#'   which assumes an approximately continuous, monotone p-value curve. Restoring continuity
		#'   by convolving the resampling distribution with a shrinking-bandwidth kernel is the
		#'   classical "smoothed bootstrap" device: Silverman (1981, "Density ratios, empirical
		#'   likelihood and cot death", \emph{Applied Statistics} 30(2):142-145) for kernel smoothing
		#'   of a resampled empirical distribution; Silverman & Young (1987, "The bootstrap: To
		#'   smooth or not to smooth?", \emph{Biometrika} 74(3):469-479) for applying that smoothing
		#'   directly to the bootstrap resampling scheme; and Hall, DiCiccio & Romano (1989, "On
		#'   smoothing and the bootstrap", \emph{Annals of Statistics} 17(2):692-704) for the
		#'   bandwidth conditions under which smoothing improves, rather than degrades, coverage
		#'   accuracy.
		#'
		#'   \strong{Implementation caveat (ad hoc, not a certified instance of the above).} The
		#'   bandwidth used here, \eqn{\hat{\sigma}/\sqrt{n}} (the raw SE-of-the-mean scale of the
		#'   response), is a pragmatic engineering choice, not one derived from or validated against
		#'   the bandwidth-selection results in the sources above. Those references smooth the
		#'   \emph{resampling distribution itself} with a bandwidth chosen to trade off bias against
		#'   variance (often shrinking slower than \eqn{n^{-1/2}}, e.g. \eqn{n^{-1/5}}-type
		#'   KDE rates); here, noise is instead added directly to each already-resampled response at
		#'   a fixed \eqn{n^{-1/2}} rate. The bandwidth is not exposed as a parameter, has no
		#'   zero-noise escape hatch (the only way to disable smoothing is to pick a different
		#'   \code{type}), and its coverage behavior has not been validated by simulation in this
		#'   package. Treat it as a discreteness patch that is qualitatively motivated by the
		#'   literature above, not a certified implementation of it.
		#' @return 	A two-sided p-value.
		compute_rand_bootstrap_two_sided_pval = function(B = 501, delta = 0, transform_responses = "none", na.rm = TRUE, show_progress = TRUE, bootstrap_type = NULL, rand_bootstrap_draws = NULL, zero_one_logit_clamp = .Machine$double.eps, type = "percentile"){
			if (should_run_asserts()) {
				private$assert_design_supports_resampling("Bootstrap randomization inference")
				assertNumeric(delta); assertCount(B, positive = TRUE); assertLogical(na.rm)
				assertChoice(tolower(type), c("percentile", "studentized", "symmetric-percentile-t", "smoothed"))
				if (private$des_obj_priv_int$response_type == "incidence" && is.null(private$custom_randomization_statistic_function) && is.null(private[["compiled_cpp_stat_fn"]])) {
					stop("Bootstrap randomization tests are not supported for incidence.")
				}
			}
			if (identical(transform_responses, "none")) {
				transform_responses = switch(
					private$des_obj_priv_int$response_type,
					continuous = "none",
					proportion = "logit",
					count = "log",
					survival = "log",
					"none"
				)
			}
			t = private$compute_treatment_estimate_during_randomization_inference()
			if (is.function(self$is_nonestimable) && isTRUE(self$is_nonestimable("estimate"))) return(NA_real_)
			if (is.list(t) && "b" %in% names(t)) t = t$b[1]
			t = as.numeric(t)[1]
			if (length(t) != 1 || !is.finite(t)) {
				if (isTRUE(private$harden)) private$cache_nonestimable_estimate("rand_bootstrap_observed_statistic_unavailable")
				return(NA_real_)
			}
			type_lc = tolower(type)
			# Studentized / symmetric-percentile-t BRT p-value: pivot each null draw by its per-draw SE.
			# "studentized" uses signed pivots (asymmetric); "symmetric-percentile-t" uses |pivot|.
			# Falls back to "percentile" when the SE is unavailable.
			if (type_lc %in% c("studentized", "symmetric-percentile-t")) {
				y0_full_stud = if (delta != 0) {
					private$shift_randomization_responses(
						y = private$y, w = private$w, delta = delta,
						transform_responses = transform_responses,
						response_type = private$des_obj_priv_int$response_type,
						inverse = TRUE, zero_one_logit_clamp = zero_one_logit_clamp
					)
				} else {
					private$y
				}
				draws_stud = if (!is.null(rand_bootstrap_draws)) {
					rand_bootstrap_draws
				} else {
					if (!is.null(private$seed)) {
						had_seed_st = exists(".Random.seed", envir = .GlobalEnv, inherits = FALSE)
						if (had_seed_st) old_seed_st = get(".Random.seed", envir = .GlobalEnv, inherits = FALSE)
						on.exit(
							if (had_seed_st) assign(".Random.seed", old_seed_st, envir = .GlobalEnv) else if (exists(".Random.seed", envir = .GlobalEnv, inherits = FALSE)) rm(".Random.seed", envir = .GlobalEnv),
							add = TRUE
						)
						set.seed(private$seed)
					}
					private$generate_rand_bootstrap_draws(B, bootstrap_type = bootstrap_type, materialize_w = TRUE)
				}
				brt_stats = private$compute_brt_null_statistics_with_se(
					draws_stud, delta, transform_responses, y0_full_stud, zero_one_logit_clamp
				)
				se_obs_stud = tryCatch(private$infer_original_se(), error = function(e) NA_real_)
				if (!is.finite(se_obs_stud) || se_obs_stud <= 0) {
					# SE unavailable: fall through to percentile
				} else {
					symmetric_pivot = identical(type_lc, "symmetric-percentile-t")
					return(private$compute_two_sided_brt_pval_studentized(t, brt_stats$t0, brt_stats$se0, delta, se_obs_stud, symmetric = symmetric_pivot))
				}
			}
			# Smoothed BRT p-value: kernel noise per draw reduces null-distribution discreteness.
			# Noise is pre-generated once per draw and reused across delta evaluations (CRN).
			if (identical(type_lc, "smoothed")) {
				draws_sm = if (!is.null(rand_bootstrap_draws) && !is.null(rand_bootstrap_draws[[1L]][["smooth_noise"]])) {
					rand_bootstrap_draws  # noise already added (e.g., by CI inversion loop)
				} else {
					d = if (!is.null(rand_bootstrap_draws)) {
						rand_bootstrap_draws
					} else {
						if (!is.null(private$seed)) {
							had_seed_sm = exists(".Random.seed", envir = .GlobalEnv, inherits = FALSE)
							if (had_seed_sm) old_seed_sm = get(".Random.seed", envir = .GlobalEnv, inherits = FALSE)
							on.exit(
								if (had_seed_sm) assign(".Random.seed", old_seed_sm, envir = .GlobalEnv) else if (exists(".Random.seed", envir = .GlobalEnv, inherits = FALSE)) rm(".Random.seed", envir = .GlobalEnv),
								add = TRUE
							)
							set.seed(private$seed)
						}
						private$generate_rand_bootstrap_draws(B, bootstrap_type = bootstrap_type, materialize_w = FALSE)
					}
					n_int = as.integer(private$n)
					sd_y = stats::sd(private$y, na.rm = TRUE)
					if (!is.finite(sd_y) || sd_y <= 0) sd_y = 1.0
					bw = sd_y / sqrt(n_int)
					for (b in seq_along(d)) d[[b]][["smooth_noise"]] = stats::rnorm(n_int, 0, bw)
					attr(d, "draws_id") = paste0(attr(d, "draws_id"), "_smoothed")
					d
				}
				t0s_sm = self$approximate_rand_bootstrap_distribution_beta_hat_T(
					B = B, delta = delta, transform_responses = transform_responses,
					show_progress = FALSE, rand_bootstrap_draws = draws_sm,
					zero_one_logit_clamp = zero_one_logit_clamp
				)
				if (!isTRUE(na.rm) && any(!is.finite(t0s_sm))) return(NA_real_)
				return(private$compute_two_sided_randomization_pval_from_t0s(t0s_sm, t))
			}
			# SMC early-stopping: evaluate the null distribution in batches; stop once the
			# Clopper-Pearson 99% band around the p-value clears the mc_stop_threshold on
			# one side. Activated by brt_mc_control (set by CI inversion or the user).
			mc_ctrl = private$brt_mc_control
			if (!is.null(mc_ctrl) && isTRUE(mc_ctrl$mc_enable) && is.finite(mc_ctrl$mc_stop_threshold)) {
				# Ensure w_b is materialized so the prefix cache gives consistent per-draw values.
				if (is.null(rand_bootstrap_draws)) {
					if (!is.null(private$seed)) {
						had_seed_smc = exists(".Random.seed", envir = .GlobalEnv, inherits = FALSE)
						if (had_seed_smc) old_seed_smc = get(".Random.seed", envir = .GlobalEnv, inherits = FALSE)
						on.exit(
							if (had_seed_smc) assign(".Random.seed", old_seed_smc, envir = .GlobalEnv) else if (exists(".Random.seed", envir = .GlobalEnv, inherits = FALSE)) rm(".Random.seed", envir = .GlobalEnv),
							add = TRUE
						)
						set.seed(private$seed)
					}
					rand_bootstrap_draws = private$generate_rand_bootstrap_draws(B, bootstrap_type = bootstrap_type, materialize_w = TRUE)
				}
				y0_full_smc = if (delta != 0) {
					private$shift_randomization_responses(
						y = private$y, w = private$w, delta = delta,
						transform_responses = transform_responses,
						response_type = private$des_obj_priv_int$response_type,
						inverse = TRUE, zero_one_logit_clamp = zero_one_logit_clamp
					)
				} else {
					private$y
				}
				smc_pval = private$compute_two_sided_brt_pval_with_sequential_mc(
					t, B, delta, transform_responses, y0_full_smc, rand_bootstrap_draws, zero_one_logit_clamp
				)
				if (!is.null(smc_pval)) return(smc_pval)
			}
			t0s = self$approximate_rand_bootstrap_distribution_beta_hat_T(
				B = B,
				delta = delta,
				transform_responses = transform_responses,
				show_progress = show_progress,
				bootstrap_type = bootstrap_type,
				rand_bootstrap_draws = rand_bootstrap_draws,
				zero_one_logit_clamp = zero_one_logit_clamp
			)
			if (!isTRUE(na.rm) && any(!is.finite(t0s))) return(NA_real_)
			private$compute_two_sided_randomization_pval_from_t0s(t0s, t)
		}
	),
	private = list(
		rand_boot_draws_counter = 0L,
		brt_mc_control = NULL,
		# Maps (transform_responses, response_type) to the shared C++ shift code used by all
		# BRT batch kernels: 0 = additive, 1 = multiplicative (log), 2 = logit,
		# 4 = multiplicative with count rounding. NULL = unsupported (callers fall back).
		rand_bootstrap_transform_code = function(transform_responses){
			if (identical(transform_responses, "none")) return(0L)
			if (identical(transform_responses, "log")) {
				return(if (identical(private$des_obj_priv_int$response_type, "count")) 4L else 1L)
			}
			if (identical(transform_responses, "logit")) return(2L)
			NULL
		},
		# Packs materialized draws into the (row-index, assignment) matrices consumed by the
		# C++ batch kernels; NULL if any draw lacks a full-size materialized assignment.
		rand_bootstrap_draw_matrices = function(rand_bootstrap_draws){
			n = as.integer(private$n)
			B = length(rand_bootstrap_draws)
			if (B == 0L) return(NULL)
			i_mat = matrix(NA_integer_, nrow = n, ncol = B)
			w_mat = matrix(NA_integer_, nrow = n, ncol = B)
			for (b in seq_len(B)) {
				draw = rand_bootstrap_draws[[b]]
				if (is.null(draw$w_b) || length(draw$i_b) != n || length(draw$w_b) != n) return(NULL)
				i_mat[, b] = as.integer(draw$i_b)
				w_mat[, b] = as.integer(draw$w_b)
			}
			list(i_mat = i_mat, w_mat = w_mat)
		},
		# Generates B bootstrap randomization draws. Each draw holds the resampled row indices
		# (i_b), the pair-aware resampled match structure (m_vec_b, matching designs only), and,
		# when materialize_w = TRUE, a fresh assignment vector w_b drawn from the design run on
		# the resampled covariates. Materialization is serial so that all delta evaluations in
		# the CI inversion share common random numbers; with materialize_w = FALSE the fresh w
		# is drawn inside each (possibly parallel) iteration instead.
		generate_rand_bootstrap_draws = function(B, bootstrap_type = NULL, materialize_w = TRUE){
			B = as.integer(B)
			draws = lapply(seq_len(B), function(b) {
				boot_draw = private$bootstrap_sample_indices(private$n, bootstrap_type)
				draw = if (is.list(boot_draw)) {
					list(i_b = as.integer(boot_draw$i_b), m_vec_b = boot_draw$m_vec_b, w_b = NULL)
				} else {
					list(i_b = as.integer(boot_draw), m_vec_b = NULL, w_b = NULL)
				}
				if (isTRUE(materialize_w)) {
					draw$w_seed = sample.int(.Machine$integer.max, 1L)
				}
				draw
			})
			if (isTRUE(materialize_w) && B > 0L) {
				use_worker = isTRUE(private$use_reusable_bootstrap_worker())
				materialize_chunk = function(idxs) {
					worker_state = if (use_worker) tryCatch(private$create_bootstrap_worker_state(), error = function(e) NULL) else NULL
					lapply(idxs, function(idx) {
						draw = draws[[idx]]
						draw$w_b = tryCatch({
							set.seed(draw$w_seed)
							if (!is.null(worker_state)) {
								private$load_bootstrap_sample_into_worker(worker_state, list(i_b = draw$i_b, m_vec_b = draw$m_vec_b))
								# [[ ]] to avoid $ partial matching (worker_des -> worker_des_priv)
								inf_priv = if (!is.null(worker_state[["worker_inf"]])) {
									worker_state[["worker_inf"]]$.__enclos_env__$private
								} else if (!is.null(worker_state[["worker_priv"]])) {
									worker_state[["worker_priv"]]
								} else {
									worker_state[["worker"]]$.__enclos_env__$private
								}
								des_obj = if (!is.null(worker_state[["worker_des"]])) worker_state[["worker_des"]] else inf_priv$des_obj
								(as.numeric(des_obj$draw_ws_according_to_design(1L)[, 1L]) + 1) / 2
							} else {
								sub_inf = private$bootstrap_subset_inference(list(i_b = draw$i_b, m_vec_b = draw$m_vec_b), smooth = FALSE)
								if (is.null(sub_inf)) NULL else {
									sub_des = sub_inf$.__enclos_env__$private$des_obj
									(as.numeric(sub_des$draw_ws_according_to_design(1L)[, 1L]) + 1) / 2
								}
							}
						}, error = function(e) NULL)
						draw
					})
				}
				draws = materialize_chunk(seq_len(B))
			}
			private$rand_boot_draws_counter = private$rand_boot_draws_counter + 1L
			attr(draws, "draws_id") = paste0("rand_boot_draws_", private$rand_boot_draws_counter)
			draws
		},
		# Loads a fresh assignment (and the sharp-null-shifted responses) into a worker whose
		# design/inference state already holds the bootstrap row subset. Mirrors the cache
		# resets of load_randomization_perm_into_worker.
		load_rand_bootstrap_assignment_into_worker = function(worker_state, draw, delta, transform_responses, y0_full, zero_one_logit_clamp = .Machine$double.eps){
			# NOTE: use [[ ]] for worker_state members — $ partial matching would resolve
			# worker_state$worker_des to worker_des_priv (an environment), a subtle bug.
			inf_priv = if (!is.null(worker_state[["worker_inf"]])) {
				worker_state[["worker_inf"]]$.__enclos_env__$private
			} else if (!is.null(worker_state[["worker_priv"]])) {
				worker_state[["worker_priv"]]
			} else {
				worker_state[["worker"]]$.__enclos_env__$private
			}
			des_obj = if (!is.null(worker_state[["worker_des"]])) worker_state[["worker_des"]] else inf_priv$des_obj
			des_priv = if (!is.null(des_obj)) des_obj$.__enclos_env__$private else worker_state[["worker_des_priv"]]
			w_new = if (!is.null(draw$w_b)) {
				as.numeric(draw$w_b)
			} else {
				if (is.null(des_obj)) stop("Reusable BRT worker has no design object to draw assignments from.")
				# draw_ws_according_to_design returns {-1,+1}; convert to internal {0,1}.
				(as.numeric(des_obj$draw_ws_according_to_design(1L)[, 1L]) + 1) / 2
			}
			if (length(w_new) != length(draw$i_b)) stop("Fresh assignment length does not match the bootstrap sample size.")
			y_sim = y0_full[draw$i_b]
			if (!is.null(draw[["smooth_noise"]])) y_sim = y_sim + as.numeric(draw[["smooth_noise"]])
			if (delta != 0) {
				y_sim = private$shift_randomization_responses(
					y = y_sim,
					w = w_new,
					delta = delta,
					transform_responses = transform_responses,
					response_type = if (!is.null(des_priv)) des_priv$response_type else private$des_obj_priv_int$response_type,
					inverse = FALSE,
					zero_one_logit_clamp = zero_one_logit_clamp
				)
			}
			if (!is.null(des_priv)) {
				des_priv$w = w_new
				des_priv$y = y_sim
			}
			inf_priv$w = w_new
			inf_priv$y = y_sim
			inf_priv$y_temp = y_sim
			inf_priv$cached_values$KKstats = NULL
			inf_priv$cached_values$beta_hat_T = NULL
			inf_priv$cached_values$s_beta_hat_T = NULL
			inf_priv$cached_values$nonestimable = NULL
			inf_priv$cached_values$nonestimable_reason = NULL
			inf_priv$cached_values$nonestimable_stage = NULL
			inf_priv$likelihood_null_warm_cache = list()
			inf_priv$cached_design_matrix = NULL
			inf_priv$cached_w_for_design_matrix = NULL
			inf_priv$cached_harden_for_design_matrix = NULL
			inf_priv$cached_reduced_X = NULL
			inf_priv$cached_X_full_for_reduced = NULL
			inf_priv$cached_keep_for_reduced = NULL
			inf_priv$cached_j_treat_for_reduced = NULL
			if (!is.null(inf_priv$compute_basic_match_data)) inf_priv$compute_basic_match_data()
			invisible(NULL)
		},
		compute_rand_bootstrap_distribution_with_reused_workers = function(rand_bootstrap_draws, delta, transform_responses, y0_full, actual_cores, show_progress = FALSE, zero_one_logit_clamp = .Machine$double.eps){
			B = length(rand_bootstrap_draws)
			chunk_n = max(1L, min(as.integer(actual_cores), as.integer(B)))
			chunk_id = ceiling(seq_len(B) / ceiling(B / chunk_n))
			chunks = split(seq_len(B), chunk_id)
			run_chunk = function(idxs) {
				worker_state = private$create_bootstrap_worker_state()
				out = numeric(length(idxs))
				for (k in seq_along(idxs)) {
					draw = rand_bootstrap_draws[[idxs[k]]]
					out[k] = tryCatch({
						private$load_bootstrap_sample_into_worker(worker_state, list(i_b = draw$i_b, m_vec_b = draw$m_vec_b))
						private$load_rand_bootstrap_assignment_into_worker(worker_state, draw, delta, transform_responses, y0_full, zero_one_logit_clamp)
						as.numeric(private$compute_bootstrap_worker_estimate(worker_state))[1L]
					}, error = function(e) NA_real_)
				}
				out
			}
			if (actual_cores <= 1L) return(as.numeric(run_chunk(seq_len(B))))
			as.numeric(unlist(private$par_lapply(
				chunks,
				run_chunk,
				n_cores = actual_cores,
				budget = 1L,
				show_progress = show_progress
			), use.names = FALSE))
		},
		# Evaluates draws[1:target] from a pre-materialized draw list, accumulating results in a
		# prefix cache keyed by (draws_id, delta, transform). Dispatches the new batch through the
		# same three-tier system as approximate_rand_bootstrap_distribution_beta_hat_T.
		get_brt_distribution_prefix = function(draws, target, delta, transform_arg, y0_full, zero_one_logit_clamp){
			draws_id = attr(draws, "draws_id")
			delta_key = formatC(as.numeric(delta), digits = 17L, format = "fg", flag = "#")
			cache_key = if (!is.null(draws_id)) paste(draws_id, delta_key, transform_arg, sep = "|") else NULL
			if (is.null(private$cached_values[["brt_prefix_cache"]])) private$cached_values$brt_prefix_cache = list()
			cached = if (!is.null(cache_key)) private$cached_values$brt_prefix_cache[[cache_key]] else NULL
			have = length(cached)
			if (have >= target) return(cached[seq_len(target)])
			new_idxs = seq.int(have + 1L, as.integer(target))
			sub_draws = draws[new_idxs]
			attr(sub_draws, "draws_id") = if (!is.null(draws_id)) paste0(draws_id, "_smc") else NULL
			has_custom = !is.null(private[["custom_randomization_statistic_function"]]) || !is.null(private[["compiled_cpp_stat_fn"]])
			has_fast_kernel = !has_custom && private$has_private_method("compute_fast_rand_bootstrap_distr")
			if (has_fast_kernel && length(draws) > 0L && !is.null(draws[[1L]][["smooth_noise"]]))
				has_fast_kernel = FALSE
			new_vals = NULL
			if (has_fast_kernel) {
				new_vals = tryCatch({
					v = private$compute_fast_rand_bootstrap_distr(y0_full, sub_draws, delta, transform_arg, zero_one_logit_clamp)
					if (!is.null(v)) as.numeric(v) else NULL
				}, error = function(e) NULL)
			}
			if (is.null(new_vals) && !has_custom && isTRUE(private$use_reusable_bootstrap_worker())) {
				new_vals = tryCatch(
					as.numeric(private$compute_rand_bootstrap_distribution_with_reused_workers(
						rand_bootstrap_draws = sub_draws, delta = delta, transform_responses = transform_arg,
						y0_full = y0_full,
						actual_cores = private$effective_parallel_cores("bootstrap", self$num_cores),
						show_progress = FALSE, zero_one_logit_clamp = zero_one_logit_clamp
					)),
					error = function(e) NULL
				)
			}
			if (is.null(new_vals)) {
				new_vals = vapply(seq_along(new_idxs), function(k) {
					tryCatch(
						suppressWarnings(private$run_rand_bootstrap_iteration(sub_draws[[k]], delta, transform_arg, y0_full, zero_one_logit_clamp)),
						error = function(e) NA_real_
					)
				}, numeric(1L))
			}
			cached = c(cached, as.numeric(new_vals))
			if (!is.null(cache_key)) private$cached_values$brt_prefix_cache[[cache_key]] = cached
			cached[seq_len(target)]
		},
		# Computes the BRT two-sided p-value with Sequential Monte Carlo early stopping.
		# Draws are evaluated in batches of mc_batch_size; after each batch (once min_draws
		# are accumulated), a Clopper-Pearson band at mc_conf_level is computed. If the band
		# lies entirely above or below mc_stop_threshold, the current p-value estimate is
		# returned. Returns NULL when SMC is disabled, draws lack materialized w_b, or the
		# batch size is >= B (which would be no batching at all).
		compute_two_sided_brt_pval_with_sequential_mc = function(t, B, delta, transform_arg, y0_full, draws, zero_one_logit_clamp){
			mc_ctrl = private$brt_mc_control
			if (is.null(mc_ctrl) || !isTRUE(mc_ctrl$mc_enable) || !is.finite(mc_ctrl$mc_stop_threshold)) return(NULL)
			if (length(draws) == 0L || is.null(draws[[1L]]$w_b)) return(NULL)
			B_int = as.integer(B)
			batch_size = min(B_int, as.integer(mc_ctrl$mc_batch_size))
			min_draws_mc = min(B_int, as.integer(mc_ctrl$mc_min_draws))
			if (batch_size <= 0L || batch_size >= B_int) return(NULL)
			conf_level = mc_ctrl$mc_conf_level
			threshold = mc_ctrl$mc_stop_threshold
			# Short-circuit: if the full B-draw distribution is already cached, skip batching.
			draws_id = attr(draws, "draws_id")
			if (!is.null(draws_id) && !is.null(private$cached_values[["rand_boot_distr_cache"]])) {
				delta_key = formatC(as.numeric(delta), digits = 17L, format = "fg", flag = "#")
				full_key = paste(B_int, delta_key, transform_arg, draws_id, sep = "|")
				full_distr = private$cached_values$rand_boot_distr_cache[[full_key]]
				if (!is.null(full_distr) && length(full_distr) >= B_int) {
					return(private$compute_two_sided_randomization_pval_from_t0s(full_distr, t))
				}
			}
			target = 0L
			repeat {
				target = min(B_int, target + batch_size)
				t0s = private$get_brt_distribution_prefix(draws, target, delta, transform_arg, y0_full, zero_one_logit_clamp)
				p_hat = private$compute_two_sided_randomization_pval_from_t0s(t0s, t)
				if (target >= B_int || !is.finite(p_hat)) return(p_hat)
				n_valid = sum(is.finite(t0s))
				if (n_valid >= min_draws_mc) {
					band = private$compute_two_sided_randomization_pval_band(t0s, t, conf_level)
					if (is.finite(band[1]) && is.finite(band[2]) && (band[2] < threshold || band[1] > threshold)) return(p_hat)
				}
			}
		},
		# One null draw returning c(t0, se0): same setup as run_rand_bootstrap_iteration but
		# calls compute_treatment_estimate_during_randomization_inference(estimate_only = FALSE)
		# so that s_beta_hat_T is populated and returned alongside the point estimate.
		run_rand_bootstrap_iteration_with_se = function(draw, delta, transform_responses, y0_full, zero_one_logit_clamp = .Machine$double.eps){
			sub_inf = private$bootstrap_subset_inference(list(i_b = draw$i_b, m_vec_b = draw$m_vec_b), smooth = FALSE)
			if (is.null(sub_inf)) return(c(t0 = NA_real_, se0 = NA_real_))
			sub_priv = sub_inf$.__enclos_env__$private
			sub_des = sub_priv$des_obj
			sub_des_priv = sub_priv$des_obj_priv_int
			w_new = if (!is.null(draw$w_b)) {
				as.numeric(draw$w_b)
			} else {
				(as.numeric(sub_des$draw_ws_according_to_design(1L)[, 1L]) + 1) / 2
			}
			if (length(w_new) != length(draw$i_b)) return(c(t0 = NA_real_, se0 = NA_real_))
			sub_des_priv$w = w_new
			y_sim = y0_full[draw$i_b]
			if (!is.null(draw[["smooth_noise"]])) y_sim = y_sim + as.numeric(draw[["smooth_noise"]])
			if (delta != 0) {
				y_sim = private$shift_randomization_responses(
					y = y_sim, w = w_new, delta = delta,
					transform_responses = transform_responses,
					response_type = sub_des_priv$response_type,
					inverse = FALSE, zero_one_logit_clamp = zero_one_logit_clamp
				)
			}
			sub_des_priv$y = y_sim
			private$sync_randomization_worker_state(sub_des, sub_inf)
			estimate = tryCatch(
				sub_inf$compute_estimate(estimate_only = FALSE),
				error = function(e) NA_real_
			)
			if (is.function(sub_inf$is_nonestimable) && isTRUE(sub_inf$is_nonestimable("estimate"))) {
				return(c(t0 = NA_real_, se0 = NA_real_))
			}
			if (is.list(estimate) && "b" %in% names(estimate)) estimate = estimate$b[1]
			t0 = as.numeric(estimate)[1L]
			se0 = as.numeric(sub_priv$cached_values$s_beta_hat_T)[1L]
			c(t0 = t0, se0 = se0)
		},
		# Fast path: reused-worker variant of compute_brt_null_statistics_with_se.
		# Calls compute_estimate(estimate_only=FALSE) inside the worker so both t0 and se0
		# are available from cached_values without re-cloning inference/design per draw.
		compute_brt_null_statistics_with_reused_workers = function(draws, delta, transform_arg, y0_full, zero_one_logit_clamp){
			B = length(draws)
			worker_state = private$create_bootstrap_worker_state()
			results_mat = matrix(NA_real_, nrow = B, ncol = 2L)
			worker_obj = worker_state[["worker"]]
			for (b in seq_len(B)) {
				draw = draws[[b]]
				results_mat[b, ] = tryCatch({
					private$load_bootstrap_sample_into_worker(worker_state, list(i_b = draw$i_b, m_vec_b = draw$m_vec_b))
					private$load_rand_bootstrap_assignment_into_worker(worker_state, draw, delta, transform_arg, y0_full, zero_one_logit_clamp)
					tryCatch(worker_obj$compute_estimate(estimate_only = FALSE), error = function(e) NULL)
					if (is.function(worker_obj$is_nonestimable) && isTRUE(worker_obj$is_nonestimable("estimate"))) {
						c(NA_real_, NA_real_)
					} else {
						wp = worker_obj$.__enclos_env__$private
						c(as.numeric(wp$cached_values$beta_hat_T)[1L],
						  as.numeric(wp$cached_values$s_beta_hat_T)[1L])
					}
				}, error = function(e) c(NA_real_, NA_real_))
			}
			list(t0 = results_mat[, 1L], se0 = results_mat[, 2L])
		},
		# Runs all BRT draws at delta and returns list(t0, se0).
		# Uses a reused-worker fast path when available; falls back to bootstrap_subset_inference.
		compute_brt_null_statistics_with_se = function(draws, delta, transform_arg, y0_full, zero_one_logit_clamp){
			B = length(draws)
			if (B == 0L) return(list(t0 = numeric(0), se0 = numeric(0)))
			if (isTRUE(private$use_reusable_bootstrap_worker()) &&
				is.null(private$custom_randomization_statistic_function) &&
				is.null(private[["compiled_cpp_stat_fn"]])) {
				result = tryCatch(
					private$compute_brt_null_statistics_with_reused_workers(draws, delta, transform_arg, y0_full, zero_one_logit_clamp),
					error = function(e) NULL
				)
				if (!is.null(result)) return(result)
			}
			results_mat = matrix(NA_real_, nrow = B, ncol = 2L)
			for (b in seq_len(B)) {
				results_mat[b, ] = tryCatch(
					suppressWarnings(private$run_rand_bootstrap_iteration_with_se(
						draws[[b]], delta, transform_arg, y0_full, zero_one_logit_clamp
					)),
					error = function(e) c(NA_real_, NA_real_)
				)
			}
			list(t0 = results_mat[, 1L], se0 = results_mat[, 2L])
		},
		# Studentized two-sided BRT p-value using signed or absolute pivots.
		# symmetric = FALSE ("studentized"): signed pivot z0 = (t0_b - delta) / se0_b;
		#   p = 2 * min(P(z0 >= z_obs), P(z0 <= z_obs)). Yields asymmetric CI under inversion.
		# symmetric = TRUE ("symmetric-percentile-t"): absolute pivot |t0_b - delta| / se0_b;
		#   p = P(|z0| >= |z_obs|). CI is symmetric around the observed estimate.
		# Draws with non-finite t0_b or se0_b excluded; 2/n floor on finite draw count.
		compute_two_sided_brt_pval_studentized = function(t, t0_b, se0_b, delta, se_obs, symmetric = FALSE){
			if (!is.finite(se_obs) || se_obs <= 0 || !is.finite(t)) return(NA_real_)
			ok = is.finite(t0_b) & is.finite(se0_b) & se0_b > 0
			n_ok = sum(ok)
			if (n_ok == 0L) return(NA_real_)
			if (isTRUE(symmetric)) {
				z0 = abs(t0_b[ok] - delta) / se0_b[ok]
				z_obs = abs(t - delta) / se_obs
				min(1, max(2 / n_ok, mean(z0 >= z_obs)))
			} else {
				z0 = (t0_b[ok] - delta) / se0_b[ok]
				z_obs = (t - delta) / se_obs
				min(1, max(2 / n_ok, 2 * min(mean(z0 >= z_obs), mean(z0 <= z_obs))))
			}
		},
		# One null draw: build the resampled sub-design/sub-inference, draw (or inject) a fresh
		# w from the design, impose the sharp null shift on the treated, and compute the statistic.
		run_rand_bootstrap_iteration = function(draw, delta, transform_responses, y0_full, zero_one_logit_clamp = .Machine$double.eps){
			sub_inf = private$bootstrap_subset_inference(list(i_b = draw$i_b, m_vec_b = draw$m_vec_b), smooth = FALSE)
			if (is.null(sub_inf)) return(NA_real_)
			sub_priv = sub_inf$.__enclos_env__$private
			sub_des = sub_priv$des_obj
			sub_des_priv = sub_priv$des_obj_priv_int
			w_new = if (!is.null(draw$w_b)) {
				as.numeric(draw$w_b)
			} else {
				# draw_ws_according_to_design returns {-1,+1}; convert to internal {0,1}.
				(as.numeric(sub_des$draw_ws_according_to_design(1L)[, 1L]) + 1) / 2
			}
			if (length(w_new) != length(draw$i_b)) return(NA_real_)
			sub_des_priv$w = w_new
			# The resampled control potential outcomes are w-invariant under the sharp null;
			# re-impose the delta shift on the freshly treated.
			y_sim = y0_full[draw$i_b]
			if (!is.null(draw[["smooth_noise"]])) y_sim = y_sim + as.numeric(draw[["smooth_noise"]])
			if (delta != 0) {
				y_sim = private$shift_randomization_responses(
					y = y_sim,
					w = w_new,
					delta = delta,
					transform_responses = transform_responses,
					response_type = sub_des_priv$response_type,
					inverse = FALSE,
					zero_one_logit_clamp = zero_one_logit_clamp
				)
			}
			sub_des_priv$y = y_sim
			private$sync_randomization_worker_state(sub_des, sub_inf)
			estimate = tryCatch(
				sub_priv$compute_treatment_estimate_during_randomization_inference(estimate_only = TRUE),
				error = function(e) NA_real_
			)
			if (is.function(sub_inf$is_nonestimable) && isTRUE(sub_inf$is_nonestimable("estimate"))) {
				estimate = NA_real_
			}
			if (is.list(estimate) && "b" %in% names(estimate)) estimate = estimate$b[1]
			as.numeric(estimate)[1L]
		}
	)
)
