#' Bootstrap Randomization Test Inference
#'
#' Abstract class implementing the bootstrap randomization test (BRT), a hybrid of the
#' nonparametric bootstrap and the randomization test of Fisher's sharp null.
#'
#' @description
#' Each of the \code{B} null draws is generated by (1) resampling \code{n} subject rows
#' \emph{with replacement} from the observed data and (2) drawing one fresh assignment
#' vector \code{w} from the actual experimental design run on the resampled covariates.
#' The test statistic computed on each such draw forms a null distribution against which
#' the observed statistic (actual data, actual \code{w}) is compared.
#'
#' @details
#' \strong{Why this is valid: the sharp null makes the science table fully known.}
#' Under Fisher's sharp null \eqn{H_0: y_i(0) = y_i(1) = y_i} for all \eqn{i}, the observed
#' outcome is the outcome regardless of assignment, so each observed row \eqn{(x_i, y_i)}
#' is a complete description of that subject: it can be paired with any \eqn{w} and the
#' outcome is still correct. Resampling rows and drawing a fresh \eqn{w} therefore
#' simulates an entire new experiment — new subjects from \eqn{\hat{F}_n} (the empirical
#' distribution of subjects), new assignment from the true, known assignment mechanism —
#' under the assumption that outcomes do not respond to treatment. Both simulation
#' ingredients are faithful to the real data-generating process under \eqn{H_0}: the
#' assignment mechanism is exact (drawn from the actual design, including sequential
#' covariate-dependent designs, since the design depends only on the covariates), and the
#' subject distribution is approximately right by the usual bootstrap argument
#' \eqn{\hat{F}_n \to F}. The \eqn{B} statistics thus consistently estimate the
#' unconditional null sampling distribution of the statistic; if \eqn{H_0} holds, the
#' observed statistic is one genuine draw from that distribution, so the p-value is
#' asymptotically uniform. If \eqn{H_0} is false, the construction \emph{still} generates
#' the null distribution (it forcibly treats \eqn{y} as invariant to \eqn{w}) while the
#' observed statistic drifts into the tail — that asymmetry is the source of power.
#'
#' \strong{How it differs from the pure randomization test.} The classic randomization
#' test conditions on the realized sample (the "science table") and is exact for any
#' \eqn{n}. The BRT is unconditional: it targets the distribution of the statistic over
#' both subject sampling and randomization, so its validity is only asymptotic
#' (inheriting the usual bootstrap smoothness/moment conditions), and the null tested is
#' the compound "sharp null AND subjects are i.i.d. draws from \eqn{F}". Exactness is
#' traded for a population-level (superpopulation) interpretation. Equivalently, the BRT
#' is a parametric bootstrap test whose "parameter" is the pair (\eqn{F}, design): the
#' design part is known exactly, \eqn{F} is plugged in via \eqn{\hat{F}_n}, and the sharp
#' null is precisely what makes \eqn{\hat{F}_n} estimable from one arm-agnostic dataset.
#' The pure randomization test is the special case where \eqn{F} is conditioned away.
#'
#' \strong{Caveats.} (1) Sampling with replacement creates exact covariate ties that never
#' occur in the original data; for matching designs, duplicates are perfect matches, so
#' bootstrap experiments are systematically better matched than fresh draws from \eqn{F}
#' would be — a persistent (not vanishing) finite-\eqn{n} perturbation of the null
#' distribution for match-dependent statistics. (Here, matched structure is carried by the
#' pair-aware bootstrap resampler and fresh \code{w} draws follow the design's own
#' randomization distribution via \code{draw_ws_according_to_design}, consistent with the
#' package's randomization test.) (2) For sequential designs the bootstrap sample needs an
#' arrival order; the i.i.d. resampling order plays that role, matching the i.i.d.-arrivals
#' assumption of the KK designs. (3) Studentization is not needed for validity but, as with
#' any bootstrap test, an asymptotically pivotal statistic improves the level's rate of
#' convergence.
#'
#' @keywords internal
InferenceRandBootstrap = R6::R6Class("InferenceRandBootstrap",
	lock_objects = FALSE,
	inherit = InferenceNonParamBootstrap,
	public = list(
		#' @description Computes the bootstrap randomization null distribution of the test
		#'   statistic under Fisher's sharp null (shifted by \code{delta}): each draw resamples
		#'   subject rows with replacement and draws one fresh assignment vector from the design.
		#'
		#' @param B  					Number of bootstrap randomization draws. Default 501.
		#' @param delta  				The null treatment effect (on the \code{transform_responses}
		#'   scale). Default 0.
		#' @param transform_responses  Type of response transformation used to impose the
		#'   sharp null shift for nonzero \code{delta}. Default "none".
		#' @param show_progress  		A flag indicating whether a progress bar should be displayed.
		#' @param debug  				If \code{TRUE}, return a list with the distribution values and
		#'   per-iteration diagnostics including error messages, warning messages, counts of each,
		#'   and summary proportions for iterations with errors, warnings, and illegal (non-finite)
		#'   values. Runs serially. Default \code{FALSE}.
		#' @param bootstrap_type 		Optional bootstrap-resampling scheme; see
		#'   \code{approximate_bootstrap_distribution_beta_hat_T} for legal values. Default \code{NULL}.
		#' @param rand_bootstrap_draws 	Optional pre-generated draws (as returned by the private
		#'   method \code{generate_rand_bootstrap_draws}) enabling common random numbers across
		#'   calls with different \code{delta} values (used by the CI inversion). Default \code{NULL}.
		#' @param zero_one_logit_clamp The clamping amount for exact 0 and 1 values when logging.
		#' @return 	When \code{debug = FALSE} (default), a numeric vector of length \code{B}
		#'   containing the null-distribution draws. When \code{debug = TRUE}, a list with:
		#'   \code{values}, \code{errors}, \code{warnings}, \code{num_errors}, \code{num_warnings},
		#'   \code{prop_iterations_with_errors}, \code{prop_iterations_with_warnings}, and
		#'   \code{prop_illegal_values}.
		approximate_rand_bootstrap_distribution_beta_hat_T = function(B = 501, delta = 0, transform_responses = "none", show_progress = TRUE, debug = FALSE, bootstrap_type = NULL, rand_bootstrap_draws = NULL, zero_one_logit_clamp = .Machine$double.eps){
			private$active_resampling_operation = "rand_bootstrap"
			on.exit(private$active_resampling_operation <- NULL, add = TRUE)
			if (should_run_asserts()) {
				private$assert_design_supports_resampling("Bootstrap randomization inference")
				private$assert_valid_bootstrap_type(bootstrap_type)
				assertNumeric(delta); assertCount(B, positive = TRUE); assertFlag(debug)
			}
			draws_supplied = !is.null(rand_bootstrap_draws)
			cache_key = paste(
				as.integer(B),
				formatC(as.numeric(delta), digits = 17, format = "fg", flag = "#"),
				transform_responses,
				if (draws_supplied) attr(rand_bootstrap_draws, "draws_id") else "fresh",
				sep = "|"
			)
			if (is.null(private$cached_values$rand_boot_distr_cache)) private$cached_values$rand_boot_distr_cache = list()
			if (!isTRUE(debug) && !is.null(private$cached_values$rand_boot_distr_cache[[cache_key]])) {
				return(private$cached_values$rand_boot_distr_cache[[cache_key]])
			}
			if (private$verbose) cat("Computing bootstrap randomization distribution...\n")
			if (!draws_supplied) {
				if (!is.null(private$seed)) {
					had_seed = exists(".Random.seed", envir = .GlobalEnv, inherits = FALSE)
					if (had_seed) old_seed = get(".Random.seed", envir = .GlobalEnv, inherits = FALSE)
					on.exit(
						if (had_seed) assign(".Random.seed", old_seed, envir = .GlobalEnv) else rm(".Random.seed", envir = .GlobalEnv),
						add = TRUE
					)
					set.seed(private$seed)
				}
				rand_bootstrap_draws = private$generate_rand_bootstrap_draws(B, bootstrap_type = bootstrap_type, materialize_w = FALSE)
			}
			# Under the sharp null with effect delta, the control potential outcomes are the
			# observed responses with the delta shift removed from the treated subjects.
			y0_full = if (delta != 0) {
				private$shift_randomization_responses(
					y = private$y,
					w = private$w,
					delta = delta,
					transform_responses = transform_responses,
					response_type = private$des_obj_priv_int$response_type,
					inverse = TRUE,
					zero_one_logit_clamp = zero_one_logit_clamp
				)
			} else {
				private$y
			}
			if (isTRUE(debug)) {
				debug_results = lapply(rand_bootstrap_draws, function(draw) {
					iter_warns = character(0)
					iter_errs = character(0)
					iter_val = withCallingHandlers(
						tryCatch(
							private$run_rand_bootstrap_iteration(draw, delta, transform_responses, y0_full, zero_one_logit_clamp),
							error = function(e) { iter_errs <<- c(iter_errs, conditionMessage(e)); NA_real_ }
						),
						warning = function(w) { iter_warns <<- c(iter_warns, conditionMessage(w)); invokeRestart("muffleWarning") }
					)
					list(val = as.numeric(iter_val)[1L], errors = iter_errs, warnings = iter_warns)
				})
				values = vapply(debug_results, function(x) as.numeric(x[["val"]])[1L], numeric(1))
				errors_list = lapply(debug_results, `[[`, "errors")
				warnings_list = lapply(debug_results, `[[`, "warnings")
				num_errors_vec = lengths(errors_list)
				num_warnings_vec = lengths(warnings_list)
				private$cached_values$rand_boot_distr_cache[[cache_key]] = values
				return(list(
					values = values,
					errors = errors_list,
					warnings = warnings_list,
					num_errors = num_errors_vec,
					num_warnings = num_warnings_vec,
					prop_iterations_with_errors = mean(num_errors_vec > 0),
					prop_iterations_with_warnings = mean(num_warnings_vec > 0),
					prop_illegal_values = mean(!is.finite(values))
				))
			}
			# Fast path: reusable worker states avoid the per-iteration design/inference
			# duplication that dominates the cost of the standard path. Custom randomization
			# statistics are excluded (compute_bootstrap_worker_estimate computes the model
			# estimate), mirroring the pure randomization test's reused-worker gating.
			if (isTRUE(private$use_reusable_bootstrap_worker()) &&
				is.null(private$custom_randomization_statistic_function) &&
				is.null(private[["compiled_cpp_stat_fn"]])) {
				t0s = private$compute_rand_bootstrap_distribution_with_reused_workers(
					rand_bootstrap_draws = rand_bootstrap_draws,
					delta = delta,
					transform_responses = transform_responses,
					y0_full = y0_full,
					actual_cores = private$effective_parallel_cores("bootstrap", self$num_cores),
					show_progress = show_progress,
					zero_one_logit_clamp = zero_one_logit_clamp
				)
				if (!is.numeric(t0s)) t0s = as.numeric(t0s)
				private$cached_values$rand_boot_distr_cache[[cache_key]] = t0s
				return(t0s)
			}
			# Warm-up guard: run one iteration serially (twice, using the second timing to skip
			# cold-start penalties) and only parallelize if computation outweighs fork overhead.
			actual_cores = private$effective_parallel_cores("bootstrap", self$num_cores)
			if (actual_cores > 1L) {
				do_warmup_iter = function() {
					tryCatch(
						private$run_rand_bootstrap_iteration(rand_bootstrap_draws[[1L]], delta, transform_responses, y0_full, zero_one_logit_clamp),
						error = function(e) NA_real_
					)
				}
				system.time(do_warmup_iter())  # First call: discarded (cold-start overhead)
				t_warmup = system.time(do_warmup_iter())[[3]]  # Second call: representative cost
				fork_overhead_estimate = if (!is.null(get_global_fork_cluster())) 0.01 else 0.3
				if (!(t_warmup * B > fork_overhead_estimate * actual_cores))
					actual_cores = 1L
			}
			t0s = unlist(private$par_lapply(seq_along(rand_bootstrap_draws), function(idx) {
				tryCatch(
					suppressWarnings(private$run_rand_bootstrap_iteration(rand_bootstrap_draws[[idx]], delta, transform_responses, y0_full, zero_one_logit_clamp)),
					error = function(e) NA_real_
				)
			}, n_cores = actual_cores, show_progress = show_progress,
			export_list = list(
				rand_bootstrap_draws = rand_bootstrap_draws,
				delta = delta,
				transform_responses = transform_responses,
				y0_full = y0_full,
				zero_one_logit_clamp = zero_one_logit_clamp
			)))
			if (!is.numeric(t0s)) t0s = as.numeric(t0s)
			private$cached_values$rand_boot_distr_cache[[cache_key]] = t0s
			t0s
		},
		#' @description Computes a bootstrap randomization two-sided p-value for Fisher's sharp
		#'   null (shifted by \code{delta}): the observed statistic (actual data, actual \code{w})
		#'   is compared against the null distribution generated by resampling rows and drawing
		#'   fresh assignments from the design.
		#'
		#' @param B  					Number of bootstrap randomization draws. Default 501.
		#' @param delta  				The null treatment effect. Default 0.
		#' @param transform_responses  Type of response transformation for the sharp null shift.
		#'   The default "none" resolves by response type (logit for proportion, log for count
		#'   and survival, identity otherwise), matching \code{compute_rand_two_sided_pval}.
		#' @param na.rm 				Remove non-finite null draws. Default \code{TRUE}.
		#' @param show_progress  		A flag indicating whether a progress bar should be displayed.
		#' @param bootstrap_type 		Optional bootstrap-resampling scheme; see
		#'   \code{approximate_bootstrap_distribution_beta_hat_T} for legal values. Default \code{NULL}.
		#' @param rand_bootstrap_draws 	Optional pre-generated draws for common random numbers
		#'   across \code{delta} values. Default \code{NULL}.
		#' @param zero_one_logit_clamp The clamping amount for exact 0 and 1 values when logging.
		#' @return 	A two-sided p-value.
		compute_rand_bootstrap_two_sided_pval = function(B = 501, delta = 0, transform_responses = "none", na.rm = TRUE, show_progress = TRUE, bootstrap_type = NULL, rand_bootstrap_draws = NULL, zero_one_logit_clamp = .Machine$double.eps){
			if (should_run_asserts()) {
				private$assert_design_supports_resampling("Bootstrap randomization inference")
				assertNumeric(delta); assertCount(B, positive = TRUE); assertLogical(na.rm)
				if (private$des_obj_priv_int$response_type == "incidence" && is.null(private$custom_randomization_statistic_function) && is.null(private[["compiled_cpp_stat_fn"]])) {
					stop("Bootstrap randomization tests are not supported for incidence.")
				}
			}
			if (identical(transform_responses, "none")) {
				transform_responses = switch(
					private$des_obj_priv_int$response_type,
					continuous = "none",
					proportion = "logit",
					count = "log",
					survival = "log",
					"none"
				)
			}
			t = private$compute_treatment_estimate_during_randomization_inference()
			if (is.function(self$is_nonestimable) && isTRUE(self$is_nonestimable("estimate"))) return(NA_real_)
			if (is.list(t) && "b" %in% names(t)) t = t$b[1]
			t = as.numeric(t)[1]
			if (length(t) != 1 || !is.finite(t)) {
				if (isTRUE(private$harden)) private$cache_nonestimable_estimate("rand_bootstrap_observed_statistic_unavailable")
				return(NA_real_)
			}
			t0s = self$approximate_rand_bootstrap_distribution_beta_hat_T(
				B = B,
				delta = delta,
				transform_responses = transform_responses,
				show_progress = show_progress,
				bootstrap_type = bootstrap_type,
				rand_bootstrap_draws = rand_bootstrap_draws,
				zero_one_logit_clamp = zero_one_logit_clamp
			)
			if (!isTRUE(na.rm) && any(!is.finite(t0s))) return(NA_real_)
			private$compute_two_sided_randomization_pval_from_t0s(t0s, t)
		}
	),
	private = list(
		rand_boot_draws_counter = 0L,
		# Generates B bootstrap randomization draws. Each draw holds the resampled row indices
		# (i_b), the pair-aware resampled match structure (m_vec_b, matching designs only), and,
		# when materialize_w = TRUE, a fresh assignment vector w_b drawn from the design run on
		# the resampled covariates. Materialization is serial and is used by the CI inversion so
		# that all delta evaluations share common random numbers; with materialize_w = FALSE the
		# fresh w is drawn inside each (possibly parallel) iteration instead.
		generate_rand_bootstrap_draws = function(B, bootstrap_type = NULL, materialize_w = TRUE){
			worker_state = if (isTRUE(materialize_w) && isTRUE(private$use_reusable_bootstrap_worker())) {
				tryCatch(private$create_bootstrap_worker_state(), error = function(e) NULL)
			} else {
				NULL
			}
			draws = lapply(seq_len(as.integer(B)), function(b) {
				boot_draw = private$bootstrap_sample_indices(private$n, bootstrap_type)
				draw = if (is.list(boot_draw)) {
					list(i_b = as.integer(boot_draw$i_b), m_vec_b = boot_draw$m_vec_b, w_b = NULL)
				} else {
					list(i_b = as.integer(boot_draw), m_vec_b = NULL, w_b = NULL)
				}
				if (isTRUE(materialize_w)) {
					draw$w_b = if (!is.null(worker_state)) {
						tryCatch({
							private$load_bootstrap_sample_into_worker(worker_state, list(i_b = draw$i_b, m_vec_b = draw$m_vec_b))
							# [[ ]] to avoid $ partial matching (worker_des -> worker_des_priv)
							inf_priv = if (!is.null(worker_state[["worker_inf"]])) {
								worker_state[["worker_inf"]]$.__enclos_env__$private
							} else if (!is.null(worker_state[["worker_priv"]])) {
								worker_state[["worker_priv"]]
							} else {
								worker_state[["worker"]]$.__enclos_env__$private
							}
							des_obj = if (!is.null(worker_state[["worker_des"]])) worker_state[["worker_des"]] else inf_priv$des_obj
							(as.numeric(des_obj$draw_ws_according_to_design(1L)[, 1L]) + 1) / 2
						}, error = function(e) NULL)
					} else {
						sub_inf = private$bootstrap_subset_inference(draw, smooth = FALSE)
						if (is.null(sub_inf)) NULL else tryCatch({
							sub_des = sub_inf$.__enclos_env__$private$des_obj
							(as.numeric(sub_des$draw_ws_according_to_design(1L)[, 1L]) + 1) / 2
						}, error = function(e) NULL)
					}
				}
				draw
			})
			private$rand_boot_draws_counter = private$rand_boot_draws_counter + 1L
			attr(draws, "draws_id") = paste0("rand_boot_draws_", private$rand_boot_draws_counter)
			draws
		},
		# Loads a fresh assignment (and the sharp-null-shifted responses) into a worker whose
		# design/inference state already holds the bootstrap row subset. Mirrors the cache
		# resets of load_randomization_perm_into_worker.
		load_rand_bootstrap_assignment_into_worker = function(worker_state, draw, delta, transform_responses, y0_full, zero_one_logit_clamp = .Machine$double.eps){
			# NOTE: use [[ ]] for worker_state members — $ partial matching would resolve
			# worker_state$worker_des to worker_des_priv (an environment), a subtle bug.
			inf_priv = if (!is.null(worker_state[["worker_inf"]])) {
				worker_state[["worker_inf"]]$.__enclos_env__$private
			} else if (!is.null(worker_state[["worker_priv"]])) {
				worker_state[["worker_priv"]]
			} else {
				worker_state[["worker"]]$.__enclos_env__$private
			}
			des_obj = if (!is.null(worker_state[["worker_des"]])) worker_state[["worker_des"]] else inf_priv$des_obj
			des_priv = if (!is.null(des_obj)) des_obj$.__enclos_env__$private else worker_state[["worker_des_priv"]]
			w_new = if (!is.null(draw$w_b)) {
				as.numeric(draw$w_b)
			} else {
				if (is.null(des_obj)) stop("Reusable BRT worker has no design object to draw assignments from.")
				# draw_ws_according_to_design returns {-1,+1}; convert to internal {0,1}.
				(as.numeric(des_obj$draw_ws_according_to_design(1L)[, 1L]) + 1) / 2
			}
			if (length(w_new) != length(draw$i_b)) stop("Fresh assignment length does not match the bootstrap sample size.")
			y_sim = y0_full[draw$i_b]
			if (delta != 0) {
				y_sim = private$shift_randomization_responses(
					y = y_sim,
					w = w_new,
					delta = delta,
					transform_responses = transform_responses,
					response_type = if (!is.null(des_priv)) des_priv$response_type else private$des_obj_priv_int$response_type,
					inverse = FALSE,
					zero_one_logit_clamp = zero_one_logit_clamp
				)
			}
			if (!is.null(des_priv)) {
				des_priv$w = w_new
				des_priv$y = y_sim
			}
			inf_priv$w = w_new
			inf_priv$y = y_sim
			inf_priv$y_temp = y_sim
			inf_priv$cached_values$KKstats = NULL
			inf_priv$cached_values$beta_hat_T = NULL
			inf_priv$cached_values$s_beta_hat_T = NULL
			inf_priv$cached_values$nonestimable = NULL
			inf_priv$cached_values$nonestimable_reason = NULL
			inf_priv$cached_values$nonestimable_stage = NULL
			inf_priv$likelihood_null_warm_cache = list()
			inf_priv$cached_design_matrix = NULL
			inf_priv$cached_w_for_design_matrix = NULL
			inf_priv$cached_harden_for_design_matrix = NULL
			inf_priv$cached_reduced_X = NULL
			inf_priv$cached_X_full_for_reduced = NULL
			inf_priv$cached_keep_for_reduced = NULL
			inf_priv$cached_j_treat_for_reduced = NULL
			if (!is.null(inf_priv$compute_basic_match_data)) inf_priv$compute_basic_match_data()
			invisible(NULL)
		},
		compute_rand_bootstrap_distribution_with_reused_workers = function(rand_bootstrap_draws, delta, transform_responses, y0_full, actual_cores, show_progress = FALSE, zero_one_logit_clamp = .Machine$double.eps){
			B = length(rand_bootstrap_draws)
			chunk_n = max(1L, min(as.integer(actual_cores), as.integer(B)))
			chunk_id = ceiling(seq_len(B) / ceiling(B / chunk_n))
			chunks = split(seq_len(B), chunk_id)
			run_chunk = function(idxs) {
				worker_state = private$create_bootstrap_worker_state()
				out = numeric(length(idxs))
				for (k in seq_along(idxs)) {
					draw = rand_bootstrap_draws[[idxs[k]]]
					out[k] = tryCatch({
						private$load_bootstrap_sample_into_worker(worker_state, list(i_b = draw$i_b, m_vec_b = draw$m_vec_b))
						private$load_rand_bootstrap_assignment_into_worker(worker_state, draw, delta, transform_responses, y0_full, zero_one_logit_clamp)
						as.numeric(private$compute_bootstrap_worker_estimate(worker_state))[1L]
					}, error = function(e) NA_real_)
				}
				out
			}
			if (actual_cores <= 1L) return(as.numeric(run_chunk(seq_len(B))))
			as.numeric(unlist(private$par_lapply(
				chunks,
				run_chunk,
				n_cores = actual_cores,
				budget = 1L,
				show_progress = show_progress
			), use.names = FALSE))
		},
		# One null draw: build the resampled sub-design/sub-inference, draw (or inject) a fresh
		# w from the design, impose the sharp null shift on the treated, and compute the statistic.
		run_rand_bootstrap_iteration = function(draw, delta, transform_responses, y0_full, zero_one_logit_clamp = .Machine$double.eps){
			sub_inf = private$bootstrap_subset_inference(list(i_b = draw$i_b, m_vec_b = draw$m_vec_b), smooth = FALSE)
			if (is.null(sub_inf)) return(NA_real_)
			sub_priv = sub_inf$.__enclos_env__$private
			sub_des = sub_priv$des_obj
			sub_des_priv = sub_priv$des_obj_priv_int
			w_new = if (!is.null(draw$w_b)) {
				as.numeric(draw$w_b)
			} else {
				# draw_ws_according_to_design returns {-1,+1}; convert to internal {0,1}.
				(as.numeric(sub_des$draw_ws_according_to_design(1L)[, 1L]) + 1) / 2
			}
			if (length(w_new) != length(draw$i_b)) return(NA_real_)
			sub_des_priv$w = w_new
			# The resampled control potential outcomes are w-invariant under the sharp null;
			# re-impose the delta shift on the freshly treated.
			y_sim = y0_full[draw$i_b]
			if (delta != 0) {
				y_sim = private$shift_randomization_responses(
					y = y_sim,
					w = w_new,
					delta = delta,
					transform_responses = transform_responses,
					response_type = sub_des_priv$response_type,
					inverse = FALSE,
					zero_one_logit_clamp = zero_one_logit_clamp
				)
			}
			sub_des_priv$y = y_sim
			private$sync_randomization_worker_state(sub_des, sub_inf)
			estimate = tryCatch(
				sub_priv$compute_treatment_estimate_during_randomization_inference(estimate_only = TRUE),
				error = function(e) NA_real_
			)
			if (is.function(sub_inf$is_nonestimable) && isTRUE(sub_inf$is_nonestimable("estimate"))) {
				estimate = NA_real_
			}
			if (is.list(estimate) && "b" %in% names(estimate)) estimate = estimate$b[1]
			as.numeric(estimate)[1L]
		}
	)
)
